# =============================================================================
# Constraints: arty_s7.xdc
# Project:     AEGIS — Adaptive FPGA-Based Side-Channel Defense
# File:        constraints/arty_s7.xdc (MODIFIED FOR ACT 2 TIMING FIX)
# Target:      Digilent Arty S7 (Xilinx Spartan-7 XC7S50-CSGA324)
#
# CHANGES FOR ACT 2:
#   Added derived clock constraint for the 50MHz AES clock (clk_aes).
#   The top-level module (aes_masked.v) now includes a clock divider-by-2
#   to create clk_aes from the input 100MHz clock.
#
# CLOCK ARCHITECTURE:
#   clk (100 MHz)  → UART RX/TX  (baud rate divisor unchanged)
#   clk_aes (50 MHz) → AES core, control FSM, HW monitor
#
# WHY THIS IS NECESSARY:
#   Boolean masking adds combinational depth that exceeds 10ns at 100MHz.
#   The 50MHz clock provides 20ns of slack, allowing the design to meet timing.
# =============================================================================

# ── Primary Clock ─────────────────────────────────────────────────────────────
# 100 MHz oscillator on Arty S7 (physical input)
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_100mhz [get_ports clk]

# ── Derived Clock ─────────────────────────────────────────────────────────────
# 50 MHz clock for AES core (generated by divide-by-2 in aes_masked.v)
# The divider is a simple toggle FF: clk_div_reg toggles at 100MHz → 50MHz output
#
# Vivado needs to know about this derived clock to properly constrain paths
# between the 100MHz and 50MHz domains.
create_generated_clock -name clk_aes_50mhz \
    -source [get_ports clk] \
    -divide_by 2 \
    [get_pins {u_control_fsm/clk}]
    # NOTE: Replace path if control_fsm is not the best reference point.
    #       Alternatively, constrain the divider FF output directly:
    #       [get_pins {clk_div_reg/Q}]

# Optional: If you want to explicitly check the divided clock
# set_max_delay -from [get_clocks sys_clk_100mhz] -to [get_clocks clk_aes_50mhz] 10.000
# set_max_delay -from [get_clocks clk_aes_50mhz] -to [get_clocks sys_clk_100mhz] 20.000

# ── Reset ─────────────────────────────────────────────────────────────────────
# BTN0 on Arty S7 — active high (push to reset)
set_property PACKAGE_PIN H6 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

# ── UART ──────────────────────────────────────────────────────────────────────
# USB-UART bridge on Arty S7
# TX: data from FPGA to PC
set_property PACKAGE_PIN D10 [get_ports tx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports tx_pin]

# RX: data from PC to FPGA
set_property PACKAGE_PIN A9 [get_ports rx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rx_pin]

# ── LEDs ──────────────────────────────────────────────────────────────────────
# LED0 — led_busy (high during encryption)
set_property PACKAGE_PIN H5 [get_ports led_busy]
set_property IOSTANDARD LVCMOS33 [get_ports led_busy]

# LED1 — led_trng_valid (high when TRNG entropy validated) — Act 3
set_property PACKAGE_PIN J5 [get_ports led_trng_valid]
set_property IOSTANDARD LVCMOS33 [get_ports led_trng_valid]

# ── Ring Oscillator Pblock ────────────────────────────────────────────────────
# Constrain all 8 ring oscillators to a small physical region to:
#   1. Maximize thermal coupling (nearby LUTs share temperature → more jitter)
#   2. Minimize routing delay variation (consistent oscillation frequency)
#   3. Isolate ROs from AES datapath (prevent cross-talk affecting timing)
#
# SLICE_X0Y0:SLICE_X3Y3 is in the bottom-left corner of the XC7S50 die,
# far from the AES core logic which Vivado places in the center.
create_pblock pblock_ring_osc
add_cells_to_pblock [get_pblocks pblock_ring_osc] [get_cells -hierarchical -filter {NAME =~ *u_trng/RO*}]
resize_pblock [get_pblocks pblock_ring_osc] -add {SLICE_X0Y0:SLICE_X3Y3}

# ── Timing exceptions ─────────────────────────────────────────────────────────
# rx_pin enters a 2-FF synchroniser in uart_rx — mark it as a false path
# since it is an asynchronous input (metastability handled in RTL).
set_false_path -from [get_ports rx_pin]

# Ring oscillator outputs are asynchronous to clk — false path
# (they are sampled by the TRNG's internal sampling register)
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *u_trng/RO*}]

# CDC toggle synchronizer: false path on the first synchronizer FF
# (metastability is handled by the 2-FF synchronizer chain)
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *trng_toggle_sync1*}]

# ── Configuration ─────────────────────────────────────────────────────────────
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
